<?php

$GLOBALS['download_and_write'] = true;
//File to read.


//$GLOBALS['datos_file'] = "index_famous_tunnel.html";
$GLOBALS['datos_file'] = trim("

index_tiltshift-car_famous.html

");
$GLOBALS['datos_file'] = trim($GLOBALS['datos_file']);

//$GLOBALS['remote_victim_host'] = "hostorigin.com/filename_or_subfolders/";
$GLOBALS['remote_victim_host'] = trim("

demo.famo.us/tiltshift-car

");
